apiVersion: v2
name: parent
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: child
    import-values:
      - data
      - data2
      - override
  # - name: child
  #   import-values:
  #     - data