{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sample.fullname" . }}
  labels:
    {{- include "sample.labels" . | nindent 4 }}  
type: Opaque
data: 
{{- include "sample.secrets" . | indent 2 }}
{{- include "sample.secretfiles" . | indent 2 }}
{{- end -}}