version: '3.8'
services:
  nginx:
  image: nginx
  # using container_name means there will only ever be one nginx container!
  container_name: nginx
  restart: always
  healthcheck:
    # test: service nginx status || exit 1
    # test: ["CMD-SHELL", "wget -O /dev/null http://localhost || exit 1"]  
    test: ["CMD", "service", "nginx", "status"]
    interval: 1m
    timeout: 5s
    retries: 3