services:
  registry:
    image: registry:2
    restart: always
    container_name: registry
    volumes:
      - "stark-docker-registry:/var/lib/registry"
    networks: 
      - registry
volumes:
  stark-docker-registry:
networks:
  registry:
    driver: bridge
    name: registry
